<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d186937b-1326-4ac7-8f2b-1a195cb554c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, no info found" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
