<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>storm rule</name>
  <uuid>4d1c8e34-e95a-4958-83dd-e2d230c630bb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Weather is storm alert 
	then set decision to "Stay home, storm is coming.";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
