<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>5e2191c3-bea6-456c-ae29-14f71fefa00d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the predicted clientdefaultedpayment is "TRUE" 
then
	set decision to a new Scoreboard where
		High risk is true ,
		the Confidence is the confidence,
		the Segment is "Unknown"; 
else
	set decision to a new Scoreboard where
		High risk is false ,
		the Confidence is the confidence,
		the Segment is "Unknown";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
