<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>balance rule</name>
  <uuid>59e93432-8544-424c-a2c1-dc98cbc31c64</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Chair/Table is more than Ratio * 1.05 
then
	set decision to "ALARM" ;
else
    set decision to "NORMAL" ;

    
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
